name: PyCosm checks and tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9] # Matching Docker container

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Code style check
      run: |
        pipenv run make black-check
        pipenv run make isort-check
        pipenv run make flake
        pipenv run make vulture
    - name: Security check
      run: pipenv run make bandit
    - name: Safety check
      run: pipenv run make safety
    - name: Static type check
      run: pipenv run make mypy
    - name: Pylint check
      run: pipenv run make pylint
    - name: Unused code check
      run: pipenv run make vulture
    - name: License check
      run: pipenv run make liccheck
    - name: Copyright check
      run: pipenv run make copyright-check
    - name: Unit tests
      run: pipenv run make test
