name: Checks and Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install tox==3.24.1
    - name: Code style check
      run: |
        tox -e black-check
        tox -e isort-check
        tox -e flake8
        tox -e vulture
    - name: Security check
      run: tox -e bandit
    - name: Safety check
      run: tox -e safety
    - name: Static type check
      run: tox -e mypy
    - name: Pylint check
      run: tox -e pylint
    - name: Unused code check
      run: tox -e vulture
    - name: License check
      run: tox -e liccheck
    - name: Copyright check
      run: tox -e copyright-check
    - name: Manifest check
      run: tox -e check-manifest
    - name: Unit tests
      run: tox -e test
