name: PyCosm checks and tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9] # Matching Docker container

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev --skip-lock
    - name: Check code formatting
      run: |
        cd src/cosm
        pipenv run make black-check
    - name: Code style check
      run: |
        cd src/cosm
        pipenv run make flake
    - name: Static type check
      run: |
        cd src/cosm
        pipenv run make mypy
    - name: Unit tests
      run: |
        cd src/cosm
        pipenv run make test
