name: Checks and Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  code_quality_check:
    name: Check Code Quality
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install tox==3.25.1
    - name: Code style check
      run: |
        tox -e black-check
        tox -e isort-check
        tox -e flake8
        tox -e vulture
    - name: Security check
      run: tox -e bandit
    - name: Safety check
      run: tox -e safety
    - name: Static type check
      run: tox -e mypy
#    - name: Pylint check
#      run: tox -e pylint
    - name: License check
      run: tox -e liccheck
    - name: Copyright check
      run: tox -e copyright-check
    - name: Manifest check
      run: tox -e check-manifest

  spell-check:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.25.0
      with:
        config_path: .spellcheck.yml

  markdown-link-check:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.md-link-check.json' 

  unit_tests:
    name: Unit Tests
    needs:
    - code_quality_check
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install tox==3.25.1
    - name: Unit Tests
      run: |
        tox -e test-unit
      shell: bash
    - name: Coverage Report
      run: tox -e coverage-report

  integration_tests:
    name: Integration tests
    needs:
    - unit_tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install tox==3.25.1
    - name: Integration Tests
      run: |
          tox -e test-integration